#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --array=1-8
#SBATCH -J mark_dup
#SBATCH -t 10:00:00
#SBATCH -p all

module load picard java

samplesheet="sample_sheet1.txt"
ref=PATH_TO_REF
threads=$SLURM_JOB_CPUS_PER_NODE
name=`sed -n "$SLURM_ARRAY_TASK_ID"p $samplesheet |  awk '{print $1}'` 
r1=`sed -n "$SLURM_ARRAY_TASK_ID"p $samplesheet |  awk '{print $2}'` 
r2=`sed -n "$SLURM_ARRAY_TASK_ID"p $samplesheet |  awk '{print $3}'`

java -jar picard.jar MarkDuplicates INPUT=./mapped_reads/$name.sorted.bam OUTPUT=$name.sorted.dedup.bam METRICS_FILE=$name_DUP_metrics.txt VALIDATION_STRINGENCY=SILENT REMOVE_DUPLICATES=true
